services:
  prestashop:
    image: prestashop/prestashop:9.0.3-8.4
    restart: always
    depends_on:
      - db
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=${DB_PASSWORD}
    volumes:
      - prestashop_data:/var/www/html
    expose:
      - "80"

  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  prestashop_data:
  db_data:
